# Degradation type
# Format: degradation_type-parameter
# Examples: 'jpeg-10', 'blur-gauss', 'blur-uni', 'inpaint-center', 
#           'inpaint-freeform1020', 'superres-bicubic'
degradation: 'inpaint-freeform2030'

# Train or Validate
mode: 'train'  # options: 'train', 'validate'


# Data paths
train_data_dir: "./datasets/imagenet/train_set_small/"
adm_checkpoint_path: "./checkpoints/imagenet64_uncond_100M_1500K.pt"
val_data_dir: "./datasets/imagenet/val_set/"
# checkpoint_path: "./logs_run_2/checkpoints/latest_checkpoint_copy.pth"

# Training params
image_size: 64
batch_size: 100
num_workers: 2
learning_rate: 1.0e-5
epochs: 100

# Diffusion params
noise_schedule: "linear"
timesteps: 1000

# Logging
log_dir: "logs_inpaint_freeform2030_train"
log_interval: 10000

