# Degradation type
# Format: degradation_type-parameter
# Examples: 'jpeg-10', 'blur-gauss', 'blur-uni', 'inpaint-center', 
#           'inpaint-freeform1020', 'superres-bicubic'
degradation: 'inpaint-freeform2030'

# Train or Validate
mode: 'train'  # options: 'train', 'validate'


# Data paths
train_data_dir: "./datasets/imagenet/train_set/"
# adm_checkpoint_path: "./checkpoints/imagenet64_uncond_100M_1500K.pt"
# val_data_dir: "./datasets/imagenet/val_set/"
checkpoint_path: "./logs_inpaint_freeform2030_train_full_07-01-2026/checkpoints/checkpoint_epoch_0003.pth"

# Training params
image_size: 64
batch_size: 80
num_workers: 0
learning_rate: 1.0e-5
epochs: 7
mixed_precision: "fp16"

# Diffusion params
noise_schedule: "linear"
timesteps: 1000

# Logging
log_dir: "logs_inpaint_freeform2030_train_full_07"
log_interval: 10000

