# Degradation type
# Format: degradation_type-parameter
# Examples: 'jpeg-10', 'blur-gauss', 'blur-uni', 'inpaint-center', 
#           'inpaint-freeform1020', 'superres-bicubic'
degradation: 'jpeg-10'

# Data paths
train_data_dir: "./datasets/imagenet_50k_train/"
# adm_checkpoint_path: "./logs/checkpoints/latest_checkpoint.pth"

# Training params
image_size: 256
batch_size: 2
num_workers: 2
learning_rate: 1.0e-4
epochs: 100

# Diffusion params
noise_schedule: "symmetric"
timesteps: 1000

# Logging
log_dir: "logs"
log_interval: 1000

