# Degradation type
# Format: degradation_type-parameter
# Examples: 'jpeg-10', 'blur-gauss', 'blur-uni', 'inpaint-center', 
#           'inpaint-freeform1020', 'superres-bicubic'
degradation: 'jpeg-10'

# Data paths
train_data_dir: "./imagenet/train"
adm_checkpoint_path: "./checkpoints/256x256_diffusion_uncond.pt"

# Training params
image_size: 256
batch_size: 1
num_workers: 0
learning_rate: 1.0e-4
epochs: 100

# Diffusion params
noise_schedule: "symmetric"
timesteps: 1000

# Logging
log_dir: "logs"
log_interval: 5

