# Degradation type
# Format: degradation_type-parameter
# Examples: 'jpeg-10', 'blur-gauss', 'blur-uni', 'inpaint-center', 
#           'inpaint-freeform1020', 'superres-bicubic'
degradation: 'jpeg-50'

# Data paths
train_data_dir: "./datasets/imagenet/train_set"
val_data_dir: "./datasets/imagenet/val_set"
# adm_checkpoint_path: "./checkpoints/imagenet64_uncond_100M_1500K.pt"
checkpoint_path: "./logs_run_2/checkpoints/latest_checkpoint.pth"

# Training params
image_size: 64
batch_size: 100
num_workers: 2
learning_rate: 1.0e-5
epochs: 100

# Diffusion params
noise_schedule: "linear"
timesteps: 1000

# Logging
log_dir: "logs_run_2"
log_interval: 100

