# Degradation type
# Format: degradation_type-parameter
# Examples: 'jpeg-10', 'blur-gauss', 'blur-uni', 'inpaint-center', 
#           'inpaint-freeform1020', 'superres-bicubic'
degradation: 'superres-bicubic'

# Train or Validate
mode: 'validate'  # options: 'train', 'validate'


# Data paths
train_data_dir: "./datasets/imagenet/train_set_small/"
#adm_checkpoint_path: "./checkpoints/imagenet64_uncond_100M_1500K.pt"
val_data_dir: "./datasets/imagenet/val_set/"
checkpoint_path: "./checkpoints/superres_latest_checkpoint.pth"
image_names_file: "./ctest10k.txt"

# Validation params
image_size: 64
batch_size: 128
num_workers: 2

# Diffusion params
noise_schedule: "linear"
timesteps: 100

# Logging
log_dir: "logs_validation/superres_bicubic-100"
log_interval: 100000

mixed_precision: "bf16"

