# Degradation type
# Format: degradation_type-parameter
# Examples: 'jpeg-10', 'blur-gauss', 'blur-uni', 'inpaint-center', 
#           'inpaint-freeform1020', 'superres-bicubic'
degradation: 'inpaint-freeform2030'

# Train or Validate
mode: 'validate'  # options: 'train', 'validate'


# Data paths
train_data_dir: "./datasets/imagenet/train_set_small/"
adm_checkpoint_path: "./checkpoints/imagenet64_uncond_100M_1500K.pt"
val_data_dir: "./datasets/imagenet/val_set/"
checkpoint_path: "./checkpoints/inpaint2030_latest_checkpoint.pth"
image_names_file: "./ctest10k.txt"
imagenet_stats_path: "./imagenet/imagenet_stats.npz"

# Validation params
image_size: 64
batch_size: 64
num_workers: 4

# Diffusion params
noise_schedule: "linear"
timesteps: 1000

# Logging
log_dir: "logs_validation/inpaint_freeform2030"
log_interval: 100000

mixed_precision: "bf16"

